export type AppLocale = 'en' | 'bn-BD'
export const supportedLocales: Array<{ id: AppLocale; label: string; nativeLabel: string }> = [
  { id: 'en', label: 'English', nativeLabel: 'English' }, { id: 'bn-BD', label: 'Bangla', nativeLabel: 'বাংলা' },
]

// English source labels are stable keys. Persisted/API values are never localized.
export const bn: Record<string, string> = {
  Home:'হোম',Dashboard:'ড্যাশবোর্ড',Workshop:'ওয়ার্কশপ',Accounting:'অ্যাকাউন্টিং',Accounts:'হিসাব',Resources:'রিসোর্স',Settings:'সেটিংস',Notifications:'নোটিফিকেশন',Messages:'বার্তা',Help:'সহায়তা',Profile:'প্রোফাইল','My Profile':'আমার প্রোফাইল',Logout:'লগআউট',Language:'ভাষা',Company:'কোম্পানি','Switch application':'অ্যাপ পরিবর্তন করুন',Workspace:'কর্মক্ষেত্র',Operations:'কার্যক্রম',System:'সিস্টেম',Overview:'সারসংক্ষেপ','Daily Books':'দৈনিক হিসাব',Procurement:'ক্রয় ব্যবস্থাপনা','Financial Control':'আর্থিক নিয়ন্ত্রণ',Resource:'রিসোর্স',People:'জনবল',Infrastructure:'অবকাঠামো',Governance:'প্রশাসন',
  Users:'ব্যবহারকারী',User:'ব্যবহারকারী',Employees:'কর্মচারী',Employee:'কর্মচারী',Projects:'প্রকল্প',Project:'প্রকল্প',Assets:'সম্পদ',Asset:'সম্পদ',Attendance:'উপস্থিতি',Leave:'ছুটি',Hiring:'নিয়োগ',Organization:'প্রতিষ্ঠান',Access:'অ্যাক্সেস',Sites:'সাইট',Documents:'নথিপত্র',Integrations:'ইন্টিগ্রেশন',Audit:'নিরীক্ষা',Email:'ইমেইল',
  'Chart of Accounts':'হিসাবের খাতসমূহ','General Ledger':'সাধারণ খতিয়ান',Reports:'রিপোর্ট','The Accountant':'অ্যাকাউন্ট্যান্ট',Inventory:'ইনভেন্টরি',Manufacturing:'উৎপাদন',Banking:'ব্যাংকিং',Sales:'বিক্রয়',Purchases:'ক্রয়',Controls:'নিয়ন্ত্রণ',Closing:'সমাপনী',
  Requisitions:'চাহিদাপত্র',Requisition:'চাহিদাপত্র',Quotations:'কোটেশন',Quotation:'কোটেশন','Compare Sheets':'তুলনামূলক বিবরণী','Compare Sheet':'তুলনামূলক বিবরণী','Purchase Orders':'ক্রয়াদেশ','Purchase Order':'ক্রয়াদেশ',Receipts:'রসিদ',Receipt:'রসিদ',Invoices:'চালানসমূহ',Invoice:'চালান',Payments:'পেমেন্ট',Payment:'পেমেন্ট',Suppliers:'সরবরাহকারী',Supplier:'সরবরাহকারী',Vendors:'বিক্রেতা',Vendor:'বিক্রেতা',Customers:'গ্রাহক',Customer:'গ্রাহক',Items:'আইটেম',Item:'আইটেম','Procurement Cases':'ক্রয় কেসসমূহ','Approval Inbox':'অনুমোদন ইনবক্স','Approval Policies':'অনুমোদন নীতিমালা','Report Builder':'রিপোর্ট নির্মাতা',
  New:'নতুন',Create:'তৈরি করুন',Add:'যোগ করুন',Edit:'সম্পাদনা',Update:'আপডেট',Save:'সংরক্ষণ',Submit:'জমা দিন',Cancel:'বাতিল',Delete:'মুছুন',Remove:'অপসারণ',Close:'বন্ধ',Open:'খুলুন',View:'দেখুন',Print:'প্রিন্ট',Download:'ডাউনলোড',Upload:'আপলোড',Attach:'সংযুক্ত করুন',Approve:'অনুমোদন',Reject:'প্রত্যাখ্যান',Confirm:'নিশ্চিত করুন',Continue:'চালিয়ে যান',Back:'পেছনে',Next:'পরবর্তী',Previous:'পূর্ববর্তী',Refresh:'রিফ্রেশ',Retry:'আবার চেষ্টা করুন',Search:'খুঁজুন',Filter:'ফিল্টার',Filters:'ফিল্টারসমূহ',Export:'এক্সপোর্ট',Import:'ইমপোর্ট',Actions:'কার্যক্রম',Action:'কার্যক্রম',Details:'বিস্তারিত',
  Status:'অবস্থা',Type:'ধরন',Category:'বিভাগ',Name:'নাম',Description:'বিবরণ',Date:'তারিখ',Time:'সময়',Amount:'পরিমাণ',Total:'মোট',Subtotal:'উপমোট',Quantity:'পরিমাণ',Qty:'পরিমাণ',Price:'মূল্য',Rate:'দর',Tax:'কর',Taxes:'করসমূহ',Discount:'ছাড়',Currency:'মুদ্রা',Address:'ঠিকানা',Phone:'ফোন',Mobile:'মোবাইল',City:'শহর',Country:'দেশ',Department:'বিভাগ',Designation:'পদবি',Branch:'শাখা',Role:'ভূমিকা',Roles:'ভূমিকাসমূহ',Shop:'শপ',Shops:'শপসমূহ',Bay:'বে',Team:'টিম',Technician:'টেকনিশিয়ান','Service Advisor':'সার্ভিস অ্যাডভাইজার','Service Engineer':'সার্ভিস ইঞ্জিনিয়ার',
  Admin:'অ্যাডমিন',Administrator:'অ্যাডমিনিস্ট্রেটর',Guard:'গার্ড',Management:'ব্যবস্থাপনা','Accounts Manager':'হিসাব ব্যবস্থাপক','Store Keeper':'স্টোর কিপার',Picker:'পিকার','Parts Manager':'পার্টস ব্যবস্থাপক','Parts Buyer / Estimator':'পার্টস ক্রেতা / এস্টিমেটর',Active:'সক্রিয়',Inactive:'নিষ্ক্রিয়',Draft:'খসড়া',Submitted:'জমাকৃত',Approved:'অনুমোদিত',Rejected:'প্রত্যাখ্যাত',Pending:'অপেক্ষমাণ',Completed:'সম্পন্ন',Closed:'বন্ধ',Cancelled:'বাতিল',Opened:'খোলা','In Progress':'চলমান',Scheduled:'নির্ধারিত',Available:'উপলভ্য',Occupied:'ব্যবহৃত',Verified:'যাচাইকৃত','Under Review':'পর্যালোচনাধীন','Pending review':'পর্যালোচনার অপেক্ষায়',Requested:'অনুরোধকৃত',Received:'গৃহীত',Issued:'জারি করা',Paid:'পরিশোধিত',Unpaid:'অপরিশোধিত',
  Yes:'হ্যাঁ',No:'না',None:'কোনোটিই নয়',All:'সব',Today:'আজ',Week:'সপ্তাহ',Month:'মাস',Loading:'লোড হচ্ছে','Loading…':'লোড হচ্ছে…','Please wait…':'অনুগ্রহ করে অপেক্ষা করুন…','No records found':'কোনো রেকর্ড পাওয়া যায়নি','No data available':'কোনো তথ্য নেই','Something went wrong':'কিছু সমস্যা হয়েছে','Try again':'আবার চেষ্টা করুন','Access denied':'প্রবেশাধিকার নেই','Not authorized':'অনুমতি নেই',Required:'আবশ্যক',Optional:'ঐচ্ছিক','Created At':'তৈরির সময়','Updated At':'আপডেটের সময়',Created:'তৈরি হয়েছে',Updated:'আপডেট হয়েছে',Notes:'নোট',Remarks:'মন্তব্য',Comments:'মন্তব্যসমূহ',Attachments:'সংযুক্তি',Evidence:'প্রমাণ',Workflow:'কর্মপ্রবাহ',Timeline:'সময়রেখা',History:'ইতিহাস',Activity:'কার্যকলাপ',
  Vehicle:'যানবাহন',Vehicles:'যানবাহনসমূহ',Registration:'রেজিস্ট্রেশন','Registration Number':'রেজিস্ট্রেশন নম্বর',VIN:'ভিআইএন',Model:'মডেল',Brand:'ব্র্যান্ড',Odometer:'ওডোমিটার',Driver:'চালক',Owner:'মালিক',Appointments:'অ্যাপয়েন্টমেন্টসমূহ',Appointment:'অ্যাপয়েন্টমেন্ট',Jobs:'জবসমূহ',Job:'জব',Tasks:'কাজসমূহ',Task:'কাজ',Services:'সেবাসমূহ',Service:'সেবা',Concerns:'সমস্যাসমূহ',Concern:'সমস্যা',Parts:'পার্টস',Part:'পার্ট',Inspection:'পরিদর্শন',Diagnosis:'ডায়াগনসিস','Quality Control':'মান নিয়ন্ত্রণ',QC:'মান নিয়ন্ত্রণ',Gatepass:'গেটপাস',Release:'রিলিজ',
  'Take photo':'ছবি তুলুন','Take person photo':'ব্যক্তির ছবি তুলুন','Take live photo':'সরাসরি ছবি তুলুন',Capture:'ছবি তুলুন',Retake:'আবার তুলুন',Camera:'ক্যামেরা','Switch camera':'ক্যামেরা পরিবর্তন','Use photo':'ছবি ব্যবহার করুন','Material Request':'উপকরণ চাহিদাপত্র','Supplier Quotation':'সরবরাহকারী কোটেশন','Purchase Receipt':'ক্রয় রসিদ','Purchase Invoice':'ক্রয় চালান','Payment Entry':'পেমেন্ট এন্ট্রি','Journal Entry':'জার্নাল এন্ট্রি','Cost Center':'কস্ট সেন্টার',Warehouse:'গুদাম',Account:'হিসাব',Ledger:'খতিয়ান',Debit:'ডেবিট',Credit:'ক্রেডিট',Balance:'ব্যালেন্স','Fiscal Year':'অর্থবছর','Opening Balance':'প্রারম্ভিক স্থিতি',Reconciliation:'সমন্বয়','Profit and Loss':'লাভ ও ক্ষতি','Balance Sheet':'স্থিতিপত্র','Cash Flow Statement':'নগদ প্রবাহ বিবরণী','Trial Balance':'রেওয়ামিল','Accounts Receivable':'প্রাপ্য হিসাব','Accounts Payable':'প্রদেয় হিসাব',
  'Requested by':'অনুরোধকারী','Assigned to':'দায়িত্বপ্রাপ্ত','Approved by':'অনুমোদনকারী','Created by':'তৈরি করেছেন','Last updated':'সর্বশেষ আপডেট','Required by':'প্রয়োজনের তারিখ','Select company':'কোম্পানি নির্বাচন করুন','Select an option':'একটি অপশন নির্বাচন করুন','Search records…':'রেকর্ড খুঁজুন…','Search…':'খুঁজুন…','No results':'কোনো ফলাফল নেই','Open navigation':'নেভিগেশন খুলুন','Close navigation':'নেভিগেশন বন্ধ করুন','Expand navigation':'নেভিগেশন প্রসারিত করুন','Collapse navigation':'নেভিগেশন সংকুচিত করুন','Save changes':'পরিবর্তন সংরক্ষণ করুন','Are you sure?':'আপনি কি নিশ্চিত?','This action cannot be undone.':'এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।',
  'Job Created':'জব তৈরি হয়েছে','SA Inspection':'এসএ পরিদর্শন','Customer Approved':'গ্রাহক অনুমোদিত','SA Reviewed':'এসএ পর্যালোচিত','Diagnosis Assigned':'ডায়াগনসিস বরাদ্দ','Diagnosis Complete':'ডায়াগনসিস সম্পন্ন','Service Assigned':'সেবা বরাদ্দ','Service Complete':'সেবা সম্পন্ন','QC Assigned':'মান নিয়ন্ত্রণ বরাদ্দ','QC Approved':'মান নিয়ন্ত্রণ অনুমোদিত','QC Rejected':'মান নিয়ন্ত্রণ প্রত্যাখ্যাত','Payment Done':'পেমেন্ট সম্পন্ন','Job Finished':'জব সম্পন্ন',Released:'রিলিজ হয়েছে',Paused:'বিরতিতে',Assigned:'বরাদ্দকৃত',Passed:'উত্তীর্ণ',Failed:'ব্যর্থ',
  Identified:'শনাক্তকৃত',Priced:'মূল্য নির্ধারিত',Declined:'প্রত্যাখ্যাত',Fulfilled:'সরবরাহ সম্পন্ন','In Stock':'স্টকে আছে','Low Stock':'স্বল্প স্টক','Out of Stock':'স্টক শেষ','Pending Procurement':'ক্রয়ের অপেক্ষায়',Reserved:'সংরক্ষিত',WIP:'চলমান কাজে',Consumed:'ব্যবহৃত','Partially Available':'আংশিক উপলভ্য','Parts Available':'পার্টস উপলভ্য','Procurement Open':'ক্রয় প্রক্রিয়া চালু','Integration Attention':'ইন্টিগ্রেশন পর্যালোচনা প্রয়োজন','Sent to Store':'স্টোরে পাঠানো হয়েছে','Request Received':'অনুরোধ গৃহীত','Part Ready':'পার্ট প্রস্তুত','Partially Ready':'আংশিক প্রস্তুত',Picked:'সংগ্রহ করা হয়েছে',
  'Procurement Review':'ক্রয় পর্যালোচনা','Quotation Collection':'কোটেশন সংগ্রহ','Compare Sheet Preparation':'তুলনামূলক বিবরণী প্রস্তুতি','GM Approval':'জিএম অনুমোদন','Audit Verification':'নিরীক্ষা যাচাই','Management Approval':'ব্যবস্থাপনা অনুমোদন','PO Creation':'ক্রয়াদেশ তৈরি','Supplier Confirmation':'সরবরাহকারী নিশ্চিতকরণ','Chalan / GRN':'চালান / পণ্য গ্রহণ নোট','Audit Physical Review':'নিরীক্ষার সরেজমিন পর্যালোচনা','Procurement File Completion':'ক্রয় ফাইল সম্পন্নকরণ','Audit Clearance':'নিরীক্ষা ছাড়পত্র','Actual Accounts':'মূল হিসাবায়ন','Bill Settlement':'বিল নিষ্পত্তি','Paid / Closed':'পরিশোধিত / বন্ধ',
  'Create requisition':'চাহিদাপত্র তৈরি করুন','Create quotation':'কোটেশন তৈরি করুন','Create purchase order':'ক্রয়াদেশ তৈরি করুন','Create invoice':'চালান তৈরি করুন','Record payment':'পেমেন্ট রেকর্ড করুন','Add item':'আইটেম যোগ করুন','Add row':'সারি যোগ করুন','Add attachment':'সংযুক্তি যোগ করুন','Upload file':'ফাইল আপলোড করুন','Choose file':'ফাইল নির্বাচন করুন','No file chosen':'কোনো ফাইল নির্বাচন করা হয়নি','View details':'বিস্তারিত দেখুন','View all':'সব দেখুন','Mark read':'পঠিত হিসেবে চিহ্নিত করুন','Sign out':'সাইন আউট',
}

export function translate(source: string, locale: AppLocale): string {
  if (locale === 'en') return source
  const leading=source.match(/^\s*/)?.[0]??'', trailing=source.match(/\s*$/)?.[0]??'', core=source.trim()
  if (!core) return source
  if (bn[core]) return `${leading}${bn[core]}${trailing}`
  const punctuation=core.match(/^(.+?)([:：])$/)
  if (punctuation && bn[punctuation[1]]) return `${leading}${bn[punctuation[1]]}${punctuation[2]}${trailing}`
  return source
}
